# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"
    - "test/**/*"
